# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI with Yarn

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }} and Yarn
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn' # cache Yarn
    - name: Install dependencies with Yarn
      run: yarn install --frozen-lockfile # use yarn install，and the--frozen-lockfile 
    - name: Build the source code (replace with your build command)
      run: yarn build  # 
    - name: Run tests (replace with your test command)
      run: yarn test # 
